export const HOME_CREDIT_LINKS = [
  {
    label: "Marinara",
    detail: "Creator",
    footerPrefix: "Created by",
    url: "https://spicymarinara.github.io/",
  },
  {
    label: "LinkAPI",
    detail: "Partner",
    footerPrefix: "Partnered with",
    url: "https://linkapi.ai/",
  },
  {
    label: "Huntercolliex",
    detail: "Art and logo",
    footerPrefix: "Art and logo by",
    url: "https://huntercolliex.carrd.co/",
  },
] as const;

export const HOME_SPECIAL_THANKS = [
  "Deci",
  "Xel",
  "Jorge",
  "Cha1latte",
  "Javedz678",
  "Teuku",
  "Shadota",
  "Romu",
  "Mm14141",
  "MagicGoddess",
  "John",
  "Pwildani",
  "Felor",
  "MuniMuni",
  "Guybrush01",
  "Joshellis625",
  "LukaTheHero",
  "Coxde",
  "JorgeLTE",
  "Seele The Seal King",
  "Loungemeister",
  "Kale",
  "Tabris",
  "GREGOR OVECH",
  "Coins",
  "Tacoman",
  "Promansis",
  "Kitsumiro",
  "Sheep",
  "Pod042",
  "Prolix",
  "PlutoMayhem",
  "Mezzeh",
  "Kuc0",
  "Exalted",
  "Yang Best Girl",
  "MidnightSleeper",
  "Geechan",
  "TheLonelyDevil",
  "Artus",
  "and you",
] as const;
